# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Yaz Makes
tagline:          'Making everything cute'
description:      'I make and sell cuddly toys at <a href="https://www.etsy.com/shop/YasMakesShop" target="_blank">YazMakesShop</a> on Etsy.'
url:              http://yasminjl.github.io
baseurl:          /

author:
  name:           'Yasmin'
  url:            https://twitter.com/yazmakes

paginate:         5

# Custom vars
version:          1.0.0

socials:
  etsy:
    name:         YazMakesShop
    url:          https://www.example.com
  instagram:
    name:         yaz.makes
    url:          https://www.example.com
  twitter:
    name:         yazmakes
    url:          https://www.example.com

github:
  repo:           https://github.com/yasminjl/yasminjl.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet
